### ISSUE TITLE
Allow user configurable parameters to functions

### ISSUE THREAD

**Issue by jusw85** [peoro/ngu.js#5]
Right now the GUI functions always run in the same way. For example, MergeEverything will always merge on all inven slots. It would be helpful to allow user configuration to drive the automation.

For example, in my branch I had the following config which merges/boosts on specific slots in order, then waits for 10s, loop.

```
{
  "boost": ["weap", 0, 1, "acc0", "cube"],
  "merge": [0,1,2,3,"weap"],
  "boostDelay": 1000,
  "mergeDelay": 1000,
  ....
}
```

I don't know the best way to implement this, but I used a TextArea in my branch. Problem is, it wasn't directly editable, but Copy-Paste works. I copied in my config whenever I wanted to change it, which gets tedious. Is there a better way to do this?

**Comment by peoro** [comment]
The problem with inputting text is that NGU (or better, Unity for web) eats keyboard events too aggressively, breaking the propagation of `keypress` events, which are the ones that input fields use.

[`src/fixes.js`](https://github.com/peoro/ngu.js/blob/master/src/fixes.js) provides a hacky fix the problem: `implementTyping(input)` implements typing on the `input` element using `keydown` events.

[`src/gui.js:221`](https://github.com/peoro/ngu.js/blob/e7567517274fdfb6851b95096d9f18a598021556/src/gui.js#L221) is how `implementTyping` is used to enable typing on the "reload NGU.js" text field. Doesn't the same work with the TextArea?

**Comment by jusw85** [comment]
In my [branch](https://github.com/jusw85/ngu.js/blob/dev/src/gui.js#L184), I used implementTyping. Typing characters worked, but arrow keys, delete, and enter didn't work, so I edited my config in a separate editor and copy-pasted it in.

Testing with current version:

``const textArea = createElement(contentDiv, `textArea`, implementTyping);``

Everything works, but enter doesn't work i.e. can't input newline.

Regardless, should we use TextArea for config for now, or do you think there's a better solution?

**Comment by peoro** [comment]
I would use the TextArea with the JSON object inside for now.  
In the future it might be nicer to use simpler input fields for each parameter independently, but doing that right now feel unnecessary and overkill.

**Comment by peoro** [comment]
Enter should work in <TextArea>s now.

Not sure why arrow keys and delete weren't working in your branch. Input fields seem to only use `keypress` events to handle printable characters (and Enter, apparently). The special keys, like arrow keys, delete, CTRL-actions etc use some other event (`keydown`, maybe?). I'm guessing that whatever event they use for special keys was handled differently by the code in this branch and the one in your fork. Anyways I don't think that finding the specific culprit is worth the effort.
